### ISSUE TITLE
Update command should enable switching of update strategy

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#10]
In some cases the user can choose from the deployment job weather to perform a rolling or recreate update.
Implement new flag "--update-strategy"

When value is "rollingupdate" in addition to image tag update, change the yaml value to
```
spec:
  strategy:
    type: RollingUpdate
```
When value is "recreate" in addition to image tag update, change the yaml value to
```
spec:
  strategy:
    type: Recreate
```
If flag is not set, then do not change the strategy (leave as is).

PS: Do not change the fields(leave as is):
```
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

More details about strategies(with yaml examples)  https://medium.com/better-programming/understanding-kubernetes-deployment-strategies-12535c3cb379

**Comment by martivo** [comment]
https://github.com/entigolabs/entigo-k8s-gitops/issues/12 regarding this ticket, we should support also Daemonset and Statefulset update strategies, but not high priority atm.

**Comment by ttrumm** [comment]
https://github.com/entigolabs/entigo-k8s-gitops/tree/v56

If no strategy is defined error:
`[error] unsupported deployment strategy: 2`

Works with
`--deployment-strategy=RollingUpdate`
`--deployment-strategy=Recreate`

**Comment by ttrumm** [comment]
https://github.com/entigolabs/entigo-k8s-gitops/releases/tag/v57

works
