### ISSUE TITLE
install.txt parsing stops when empty line encountered.

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#13]
The parsin of install.txt stops when empty line is found.
The tool should always parse the file to the end. If empty line or line starting with # found then skip them. If some other content is found that can not be parsed show warning in log.

**Comment by kertkukk** [comment]
Implemented in [Release 53](https://github.com/entigolabs/entigo-k8s-gitops/releases/tag/v53) @martivo

**Comment by martivo** [comment]
It is now improved but there is an issue with some fields. I wrote details to your slack.

**Comment by martivo** [comment]
The double space is a separate issue. This one is fixed.
