### ISSUE TITLE
Gitops tool does not update initContainers images in yaml

### ISSUE THREAD

**Issue by ttrumm** [entigolabs/entigo-k8s-gitops#19]
Example output of gitops tool run
`changing keys [spec.template.spec.containers.*.image, spec.containers.*.image, spec.jobTemplate.spec.template.spec.containers.*.image] to gaudicrm.azurecr.io/cm-web:qa-1037`

Can we change initContainers images as well in yaml files?
`spec.template.spec.initContainers`

**Comment by kertkukk** [comment]
I think yes you can.

**Comment by ttrumm** [comment]
Yes it works from v62

**Comment by ttrumm** [comment]
gut
