### ISSUE TITLE
Add --quiet flag

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#2]
If the application is used in a dedicated environment then it creates very many lines of git progress. See attached screenshot. When --quiet flag is added only print errors and information what is being updated.

![Screenshot_20201126_154711](https://user-images.githubusercontent.com/29144235/100359519-56d70f00-3000-11eb-9e30-297cc33ae0f4.png)

--quiet flag output should be something like this
```
Updating <image> in path <path> of git <git url>
git clone was successful
git commit was successful
git push was successful
```
In case of errors display errors.

**Comment by kertkukk** [comment]
Implemented in [52a5cbb0](https://github.com/entigolabs/entigo-k8s-gitops/commit/52a5cbb0efc26556d7047e16d63bc6a9451ba1e9) @martivo
