### ISSUE TITLE
Gitops formats bash scripts into one-liners.  

### ISSUE THREAD

**Issue by MariiAnet** [entigolabs/entigo-k8s-gitops#20]
ConfigMap YAML before GitOps:
<img width="1263" alt="Screenshot 2021-11-01 at 09 44 33" src="https://user-images.githubusercontent.com/32903050/139638517-d25dbba0-d1ea-4087-8553-f362dc320a17.png">

ConfigMap YAML after GitOps:

<img width="1339" alt="Screenshot 2021-11-01 at 09 44 39" src="https://user-images.githubusercontent.com/32903050/139638487-d427f3e5-cdc9-49a9-a801-ce909a3eb1f2.png">

ConfigMap YAML should stay the same after Gitops tool does it's thing. :)

**Comment by entigo-mart-erlenheim** [comment]
Just in case, the data part can be any file type, e.g. json, yaml, bash, configuration properties etc. Maybe use the filename extension to check which formatting is needed? Or I guess, best would be to try to just preserve the original formatting.

**Comment by MariiAnet** [comment]
Did some testing and it seems like Gitops will format ConfigMaps into one-liners when there are spaces at the end of any line.

**Comment by kertkukk** [comment]
Released a new version - [Release 80](https://github.com/entigolabs/entigo-k8s-gitops/releases/tag/v80). Does it now do what it needs? @MariiAnet

**Comment by MariiAnet** [comment]
Works as expected! Thanks! :)
