### ISSUE TITLE
Abilty to use ENV variables and command parameters/arguments.

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#5]
If program parameter is not set then we should look for it in ENV. This goes for all possible parameters.

Example:
```
export KEY_FILE="/my_env/my_ssh_key_rsa"
gitops update ... 
```
Key file is taken from /my_env/my_ssh_key_rsa
```
export KEY_FILE="/my_env/my_ssh_key_rsa"
gitops update ... --key-file=/other_key_dsa
```
Key file is taken from /other_key_dsa

Same logic should be with all parameters.

**Comment by kertkukk** [comment]
Implemented in [bdd1266](https://github.com/entigolabs/entigo-k8s-gitops/commit/bdd1266756c955012b67bf9f0230cd2c8c15abe7) @martivo
