### ISSUE TITLE
Add possibility to maintain the current registry used (--keep-registry=true)

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#6]
Currently when the yaml has:
```image: some.registry.com/some/project/webserver:1```

and we run the `gitops update with --image webserver:2`
the resulting yaml is

```image: webserver:2```

Add flag "--keep-registry=true" In case of false work as it works now, in case of true result should be
```image: some.registry.com/some/project/webserver:2```

**Comment by kertkukk** [comment]
Implemented in [bb4eee0e](https://github.com/entigolabs/entigo-k8s-gitops/commit/bb4eee0e204e269bd4648fadc5cd5fefdf891465) @martivo

**Comment by martivo** [comment]
Works!
