### ISSUE TITLE
Check default values for parameters 

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#9]
Seems like sometimes the default values are not correctly set when they are not defined.

**Comment by kertkukk** [comment]
I assume that this understanding came from situation if some flag value contained `-l` value, e.g. Then program got unintentional logging level. Fixed in [8010cdba](https://github.com/entigolabs/entigo-k8s-gitops/commit/8010cdba681db5412129f622c28d29786cacff75) @martivo
